---
name: VanishAll
author: IvanCraft623
description: "A simple plugin to Vanish players"
version: 0.0.1
main: IvanCraft623\VanishAll\VanishAll
api: 3.0.0
permissions:
  vanisall.use:
    default: op
    description: Allow use VanishAll features!
...
